mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    map-underscore-to-camel-case: true
    # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


#linux
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: ldy
    password: "160626"

#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ems?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 160626

  data:
    redis:
      # 连接地址
      host: "localhost"
      # 端口
      port: 6379
      # 数据库
      database: 0
      # 用户名，如果有
      # username:
      # 密码，如果有
      # password:
      # 连接超时
      connect-timeout: 5s
      # 读超时
      timeout: 5s
#  mail:
#    #smtp服务主机  qq邮箱则为smtp.qq.com
#    host: smtp.qq.com
#    #服务协议
#    protocol: smtp
#    # 编码集
#    default-encoding: UTF-8
#    #发送邮件的账户
#    username: 1620977923@qq.com
#    #授权码
#    password: dpnzyromsxzfdaac
#    test-connection: true
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true

#redis:
#  host: 127.0.0.1
#  port: 6379